### ISSUE TITLE
Beautify Removes/Collapses Lines Between Elements

### ISSUE THREAD

**Issue by tackyjan** [brackets-beautify/brackets-beautify#101]
Hello.

I have CSS that looks like the following:
```css
.fruit {
}

.apple {
    color: red;
}

.orange {
    color: orange;
}

.banana {
    color: yellow;
}
```
After running Beautify it looks like this:
```css
.fruit {}
.apple {
    color: red;
}
.orange {
    color: orange;
}
.banana {
    color: yellow;
}
```
Note the two things that happened after Beatifying: the "empty" CSS element (fruit) was collapsed in to one line and the line spaces between each CSS element were removed.

Collapsing the empty CSS element isn't really that big of a deal to me although if I can stop it from doing that I would like to know.

The thing I really don't like is "crunching" all the CSS elements together by removing the lines in-between each. This makes the CSS look too busy, crowded, etc. I put the lines there for readability and I would like to keep them there after running Beautify.

Is there a way to configure Beautify to address these two issues?

Thank you.
