### ISSUE TITLE
ignore front matter YAML syntax

### ISSUE THREAD

**Issue by MortalCatalyst** [brackets-beautify/brackets-beautify#141]
Is there a way to add a type to ignore in the beautifier config?

When I add YAML front matter http://jekyllrb.com/docs/frontmatter/

``` yaml
 ---
layout: post
title: Blogging Like a Hacker

---
```

When I put front matter in my index.html and beautify the file the html works great but the yaml becomes

```
    ---- layout: post title: Blogging Like a Hacker ----
```

which wrecks its usage.
