### ISSUE TITLE
CSS Double linespace

### ISSUE THREAD

**Issue by tempo22** [brackets-beautify/brackets-beautify#15]
Hi,

thanks a lot for this extansion, it's awesome.

I have just a small question about CSS beautifying, whenever i use it all my properties are getting a double line break like this
```css
 img {

    height: 25px;

    width: auto;

}
```
Is it an expected behavior or it is something that can be fixed in the beautify-css.js ?
