### ISSUE TITLE
Less formatting - variable interpolation and mixins with multiple variables 

### ISSUE THREAD

**Issue by retan** [brackets-beautify/brackets-beautify#222]
LESS files are not aligned properly if:
1. variable interpolation is used.
--- this
```css
.class-@{name} {
    display: block;
}
```
--- becoms this
```css
.class-@ {
    name
}

{
    display: block;
}
```

2. mixins with multiple parameters
--- this
```css
.mymixin(@color: #ccc; @border-width: 1px)  {
    border: @border-width solid @color;
}
```
--- becomes this
```css
.mymixin(@color: #ccc;
@border-width: 1px) {
    border: @border-width solid @color;
}
```
I would appreciate a fix.
(by the way this extension works a way better than the dedicated Format LESS StyleSheet, which outputs a total mess!!)
