### ISSUE TITLE
Formatting within CSS @media queries doesn't follow newline_between_rules

### ISSUE THREAD

**Issue by Smiley43210** [brackets-beautify/brackets-beautify#237]
The beautifier doesn't respect the `"newline_between_rules": true` option when formatting style rules within a media query. This happens for CSS within .html files and .css files. I was unable to test the output first on http://jsbeautifier.org/ because there does not seem to be an option on the interface for this.

### Input:
```css
.foo {
color: #CCC;
}
.bar {
color: #DDD;
}
@media screen and (max-width: 500px) {
.foo {
color: #FFF;
}
.bar {
color: #000;
}
}
```

### Expected After Beautify:
```css
.foo {
	color: #CCC;
}

.bar {
	color: #DDD;
}

@media screen and (max-width: 500px) {
	.foo {
		color: #FFF;
	}

	.bar {
		color: #000;
	}
}
```

### Actual After Beautify:
```css
.foo {
	color: #CCC;
}

.bar {
	color: #DDD;
}

@media screen and (max-width: 500px) {
	.foo {
		color: #FFF;
	}
	.bar {
		color: #000;
	}
}
```

Using Beautify 2.4.0 on Brackets 1.8.
