### ISSUE TITLE
Beautifier is breaking css urls

### ISSUE THREAD

**Issue by mpbunch** [brackets-beautify/brackets-beautify#270]
**Details about your environment:**
* Brackets Version: 1.13.0-17696
* Brackets Beautify Version: 2.6.1

Issue:
new/empty stylesheet with the following:
```css
class{ background: url(http://someurl/img.png) }
```

becomes the following:
```css
.class {
  background: url(http: //someurl/img.png) }
```

Notice the malformed url: `http:[space]//...`
