### ISSUE TITLE
CSS beautifing breaks when css starts with new line.

### ISSUE THREAD

**Issue by MikeSpock** [brackets-beautify/brackets-beautify#50]
Reproduction:
Copy this snippet to a css file:

``` css
html,body,table{
    margin:0;padding:0;
    font-size:13px;
    font-family: Verdana,Arial,Helvetica,sans-serif,sans;
    color:black;
}
```

Beautifying works perfectly.
Hit an enter before the content, and beautify it again. Beautifier puts a double linebreak after every line.
