### ISSUE TITLE
Renaming CSS selectors with attributes

### ISSUE THREAD

**Issue by thaneuk** [brackets-beautify/brackets-beautify#73]
If I beautify
```css
p [title] { text-decoration: underline; }
```
I get
```css
p[title] {
	text-decoration: underline;
}
```
Which is a different selector, only found this issue with [ ] attributes.
